repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: go fmt ./...
        pass_filenames: false
        language: system
        types: [go]

      - id: go-vet
        name: go vet
        entry: go vet ./...
        pass_filenames: false
        language: system
        types: [go]

      - id: go-mod-tidy
        name: go mod tidy
        entry: go mod tidy
        pass_filenames: false
        language: system
        types: [go]
